### ISSUE TITLE
fse.rmSync is not a function when using Serverless CI/CD

### ISSUE THREAD

**Issue by cinjoff** [danieluhm2004/serverless-webpack-prisma#2]
Hi,

Thanks for the nice package. 

Running this as `serverless deploy ...` from my machine is fine.

But Serverless CI/CD is failing me:

CI output:
```
...
Serverless: Copy prisma schema for AuthorizerFunction...
Serverless: Generate prisma client for AuthorizerFunction...
Serverless: Remove unused prisma engine: 
Serverless: - node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x

 Type Error ----------------------------------------------
  TypeError: fse.rmSync is not a function
      at /api/node_modules/serverless-webpack-prisma/src/index.js:54:13
      at Array.forEach (<anonymous>)
      at ServerlessWebpackPrisma.onBeforeWebpackPackage (/api/node_modules/serverless-webpack-prisma/src/index.js:51:21)
      at PluginManager.runHooks (/api/node_modules/serverless/lib/classes/PluginManager.js:573:41)
      at PluginManager.invoke (/api/node_modules/serverless/lib/classes/PluginManager.js:612:20)
      at async PluginManager.spawn (/api/node_modules/serverless/lib/classes/PluginManager.js:635:5)
```

serverless.yml
```
...
webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules: true
    
package:
   individually: true
```

webpack.config.js
```
const path = require("path");
const slsw = require("serverless-webpack");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const nodeExternals = require("webpack-node-externals");

const { isLocal } = slsw.lib.webpack;

module.exports = {
  entry: slsw.lib.entries,
  mode: isLocal ? "development" : "production",
  devtool: "source-map",
  externals: [nodeExternals()],
  resolve: {
    extensions: [".ts", ".tsx"],
    alias: {
      lib: path.resolve(__dirname, "lib"),
      core: path.resolve(__dirname, "core"),
    },
  },
  output: {
    libraryTarget: "commonjs2",
    path: path.join(__dirname, ".webpack"),
    filename: "[name].js",
  },
  target: "node",
  optimization: {
    minimize: false,
  },
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        loader: "ts-loader",
        exclude: [
          path.resolve(__dirname, "node_modules"),
          path.resolve(__dirname, ".serverless"),
          path.resolve(__dirname, ".webpack"),
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: true,
        },
      },
    ],
  },
  plugins: [new ForkTsCheckerWebpackPlugin()],
};
```

Would you have any idea? Any help is appreciated!

**Comment by danieluhm2004** [comment]
Hello.

Thank you for your interest in the package and for leaving an issue.

We are currently in the process of removing unnecessary engines with the fs-extra library. Perhaps there was an error in the process.

The fs.rmSync function has been added to the 14.14.0+ version, but perhaps the serverless CI is using the version below.

Moving on to 1.0.4, changed to removeSync instead of rmSync so that it can be used in lower versions as well. It would be good to update the version to version 1.0.4 and proceed with the distribution.

thank you. :)

**Comment by danieluhm2004** [comment]
Let's close the issue for now. If there is a problem after checking, please open the issue again.

Thank you :)
